### ISSUE TITLE
Would like to contribute

### ISSUE THREAD

**Issue by ragavsathish** [INCF/eeg-database#116]
Hi Team,

I would like to contribute to this repo. I configured the workspace in eclipse. Please guide to start with the code.

**Comment by jezekp** [comment]
Hi, 

Thank you for your interest. But from you post I do not know how you would like to contribute?

**Comment by ragavsathish** [comment]
Shall I start with building java doc and maven site ?  Will that be helpful ?
It would be help me to understand the workflow too .

**Comment by jezekp** [comment]
Yes, you can. Thank you for your help
