### ISSUE TITLE
Accept request role does not work

### ISSUE THREAD

**Issue by jezekp** [INCF/eeg-database#118]
When a user request for a role in a group I get an error message:

Group 21 has more than one owner license!

Moreover a "send request" text on the button (image below) seems to me incorrect because I am assigning a role not sending request.

Server: Production. 
Not tested on testing environment

![image](https://cloud.githubusercontent.com/assets/1769981/6643461/ad89d852-c9ac-11e4-8055-7283898c4165.png)

**Comment by rinkesj** [comment]
It's problem of new created groups. Jakub Danek created migration script for existing groups when licenses was created and totally forgot to create owner license to new groups. Its fixed now but data on test and production servers are corrupted. I will send you sql script for repairing.
