### ISSUE TITLE
JET 2015 - license redesign

### ISSUE THREAD

**Issue by rinkesj** [INCF/eeg-database#122]
Create order with public experiment is not working now, there is no dropdownchoice for selecting license and page just show error message "You must select license for all experiments and experiment packages".

Check these added comments:
https://github.com/INCF/eeg-database/commit/7a1945f31bd7cdd68f30da1d44a1867dfb75ba34

If it is not complete now then it is ok but next time don't commit not working state in master branch. You are not alone who is working on it.

**Comment by jezekp** [comment]
Is it fixed?

**Comment by stebjan** [comment]
It looks like. There is no problem with ordering public experiments.
