### ISSUE TITLE
A data file is required when an existing experiment is edited.

### ISSUE THREAD

**Issue by jezekp** [INCF/eeg-database#124]
When I want to edit an existing experiment I have to go through the wizard. At the last step I am forced to add a data file. However I do not want to add a new file when I only edit metadata.

entovironments: production, test.

**Comment by rinkesj** [comment]
Wizard was changed - data files are required. But don't know why.

changed in commit https://github.com/INCF/eeg-database/commit/10329975a13b009495453d213388ba83a8d3a4c3

**Comment by rinkesj** [comment]
After metadata commit https://github.com/INCF/eeg-database/commit/055750df26efc48db4baf0dd798fa00dc3c2b02a data files are required only for new created experiments. Data files is not required in editation.
