### ISSUE TITLE
Licenses management

### ISSUE THREAD

**Issue by moucek** [INCF/eeg-database#131]
When you are an administrator you can manage licenses
menu Administration - Manage licenses - Add license
change the form 
- Name - there is a bug - should accept common characters and numerals
- Description - as it is
- Price - will not be here
- Type - change to Non-commercial, Commercial
- License file change to choice of link or file attachment, change the fform fields according to choice

**Comment by jakub-krauz** [comment]
Is there any restriction on characters allowed in the "Name" field?

**Comment by jakub-krauz** [comment]
No restriction for now. Closed.
