### ISSUE TITLE
Licenses and cart

### ISSUE THREAD

**Issue by moucek** [INCF/eeg-database#133]
When experiments are added in cart
- reorganize the view of the window for some better look
- license can be still re-chosen
- add the buttion Download for all non-paid licences
- when a paid license is chosen show the following announcemt: "We apologize, the transaction cannot be carried out due to organizational reasons".

**Comment by jakub-krauz** [comment]
Meeting with Petr Ježek 19. 11. 2015:
* Purchase should be confirmed on the Cart page before downloading items
* No need to treat paid licenses for now (they won't be available until an admin creates one)
* After purchase confirmation a direct link to download the whole content of the cart would be great
