### ISSUE TITLE
Difference between ROLE_USER and ROLE_READER

### ISSUE THREAD

**Issue by stebjan** [INCF/eeg-database#82]
If I register via registration, I get the ROLE_USER authority. If I am added via vizard or "add person" button, I get the ROLE_READER authority. Is this only this difference, or is there different access restrictions?

**Comment by jezekp** [comment]
Is this solved?

**Comment by stebjan** [comment]
We still have both roles, but I did not find any diference. But this issue is just a question. We can close it IMO.
